#include "OpenKNX/Network/TelegramJson.h" // defines OPENKNX_TELEGRAMJSON
#if defined(OPENKNX_TELEGRAMJSON) && defined(OPENKNX_WEBMONITOR)

#include "OpenKNX/Network/Webserver/GroupMonitor.h"
#include "OpenKNX.h"
#include "OpenKNX/Network/Module.h"
#include "OpenKNX/Network/Webserver/Webserver.h"
#include "webassets.h" // generated by OGM-Common/scripts/pio/prepare.py from web/assets/
#include <LittleFS.h>
#include <cstring>

namespace OpenKNX
{
    namespace Network
    {
        // groupmonitor.css/groupmonitor.js liegen in web/assets/ und werden dort
        // minifiziert + gzip-komprimiert in webassets.h eingebettet. Der HTML-
        // Seitenrumpf (gmPage) bleibt hier — kein separat abrufbares Asset.

        static const char gmPage[] =
            "<h1>Gruppenmonitor <span id='gm-status' class='gm-status gm-status-sm'>Verbinde&hellip;</span></h1>"
            "<div class='gm-bar'>"
            "<label><input type='checkbox' id='gm-scroll' checked> Autoscroll</label>"
#if MASK_VERSION != 0x091A
            // Not on a router: busmonitor mode takes the TP-UART out of normal
            // processing, which on 0x091A would stop TP<->IP routing, not just monitoring.
            "<label title='Im Busmonitor-Modus werden keine KNX-Telegramme mehr verarbeitet!'>"
            "<input type='checkbox' id='gm-busmon'>"
            " <span class='gm-busmon-warn'>&#x26A0; Busmonitor</span></label>"
#endif
            "<span class='gm-spacer'></span>"
            "<button type='button' id='gm-startstop'></button>"
            "<button type='button' id='gm-clear'>Leeren</button>"
            "</div>"
            "<div class='gm-tablewrap'>"
            "<table id='gm-table'>"
            "<thead><tr><th>Zeit</th><th>Flags</th><th>Quelle</th><th>Ziel</th>"
            "<th>Typ</th><th>Hauptgruppe</th><th>Mittelgruppe</th><th>Name</th><th>Value</th><th>DPT</th><th>Daten (hex)</th><th>Len</th></tr></thead>"
            "<tbody id='gm-body'></tbody>"
            "</table>"
            "</div>";

        // The page reads GA names from /openknx_ga.tsv itself -- the backend holds no
        // name strings. Served here, not via the file manager: that needs OPENKNX_WEBFS.
        namespace
        {
            struct GaCtx
            {
                File f;
            };

            size_t gaRead(void* ctx, uint8_t* buf, size_t maxLen)
            {
                return static_cast<GaCtx*>(ctx)->f.read(buf, maxLen);
            }

            void gaCleanup(void* ctx)
            {
                GaCtx* c = static_cast<GaCtx*>(ctx);
                c->f.close();
                delete c;
            }
        } // namespace

        // ── Setup ─────────────────────────────────────────────────────────────────

        void GroupMonitor::setup()
        {
            // Nur einmal registrieren – setup() kann bei Webserver-Neustart erneut
            // aufgerufen werden, der TP-Callback darf sich aber nicht aufstapeln.
            if (_initialized) return;
            _initialized = true;

            openknxNetwork.webserver.addMenuItem("Gruppenmonitor", "/groupmonitor", 110);

            openknxNetwork.webserver.addRoute(WEB_GET, "/assets/groupmonitor.css",
                                              Webserver::Asset(WebAssets::groupmonitor_css_mime, WebAssets::groupmonitor_css_gz, sizeof(WebAssets::groupmonitor_css_gz)));
            openknxNetwork.webserver.addRoute(WEB_GET, "/assets/groupmonitor.js",
                                              Webserver::Asset(WebAssets::groupmonitor_js_mime, WebAssets::groupmonitor_js_gz, sizeof(WebAssets::groupmonitor_js_gz)));
            openknxNetwork.webserver.addStylesheet("/assets/groupmonitor.css");
            openknxNetwork.webserver.addJavaScript("/assets/groupmonitor.js");

            openknxNetwork.webserver.addRoute(WEB_GET, "/groupmonitor",
                                              [](WebRequest&, WebResponse& res) {
                                                  res.setContentType("text/html");
                                                  res.setLayout(true);
                                                  res.sendStatic(gmPage);
                                              });

            // Streamed, not read into RAM: the file can be a few dozen KB.
            openknxNetwork.webserver.addRoute(WEB_GET, "/groupmonitor/ga.tsv",
                                              [](WebRequest&, WebResponse& res) {
                                                  GaCtx* ctx = new GaCtx{LittleFS.open("/openknx_ga.tsv", "r")};
                                                  res.setContentType("text/tab-separated-values; charset=utf-8");
                                                  // No file -> empty table, not 404: the columns end up empty
                                                  // either way, but a 404 is logged as a warning on every view.
                                                  if (!ctx->f)
                                                  {
                                                      delete ctx;
                                                      res.send("");
                                                      return;
                                                  }
                                                  res.sendStream((size_t)ctx->f.size(), gaRead, gaCleanup, ctx);
                                              });

            // Für "tp" wird nichts registriert -- reiner Sender. Der Busmonitor-Zustand
            // ist ein Feld in "status", ein eigener Ausgangs-Key wäre überflüssig.
            // /groupmonitor/state entfällt: einziger Konsument war das eigene Skript.
#if MASK_VERSION != 0x091A
            openknxNetwork.webserver.ui.receiveMessage([this](const char* key, const char* data, size_t len) {
                // Record only -- this is the network callback. loop() switches.
                if (strcmp(key, "busmon") != 0 || len == 0) return;
                _pendingBusmon = (data[0] == '0') ? 0 : 1;
            });
#endif

            // Paralleler Tap am KNX-Stack vorbei: jedes vom TP-UART empfangene Frame
            // landet im onFrame()-Callback (loop-Kontext, gleicher Task wie der Webserver).
            openknxNetwork.tpUart().registerReceivedFrame(
                [](TPUart::Frame& f) { openknxNetwork.groupmonitor.onFrame(f); });
        }

        // ── Busmonitor switching ────────────────────────────────────────────────────

        void GroupMonitor::loop()
        {
#if MASK_VERSION != 0x091A
            if (_pendingBusmon < 0) return;
            const int8_t cmd = _pendingBusmon;
            _pendingBusmon = -1;

            auto& dll = openknxNetwork.tpUart();
            if (cmd == 0)
                dll.reset();
            else
                dll.startMonitoring();
#endif
        }

        // ── Frame → JSON → Broadcast ────────────────────────────────────────────────

        void GroupMonitor::onFrame(TPUart::Frame& frame)
        {
            if (!frame.isFrame()) return;
            if (!openknxNetwork.webserver.ui.hasClients()) return;

            // Throttle here rather than fill the ring: after a slow tick the TP-UART
            // hands over several buffered frames while the drain runs once per loop(). A
            // dropped telegram beats overtaking a healthy client and disconnecting it.
            if (openknxNetwork.webserver.txFree() < openknxNetwork.webserver.txCapacity() / 4) return;

            // _json keeps its capacity across calls (reset() only clears content), so
            // building the message here does not allocate once warmed up.
            _json.reset();
            OpenKNX::Network::buildTelegramJson(frame, _json);

            openknxNetwork.webserver.ui.sendMessage("tp", _json.c_str());
        }

    } // namespace Network
} // namespace OpenKNX

#endif // OPENKNX_TELEGRAMJSON && OPENKNX_WEBMONITOR
